# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      -
        name: Install
        run: npm ci
      -
        name: Build
        run: |
          npx linguist release
          npm run build
      -
        name: Archive built artifacts
        run: (cd dist && tar czf bezier-werewolf-react.tgz ./*)
      -
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          asset_name: bezier-werewolf-react-$tag.tgz
          file: dist/bezier-werewolf-react.tgz
          tag: ${{ github.ref }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bezier-werewolf-react:latest,${{ secrets.DOCKER_USERNAME }}/bezier-werewolf-react:${{ github.ref_name }}
